#!/usr/bin/env python3
"""Writes regions.tf and peering.tf for the supported regions. Terraform
cannot loop over providers, so one module block per region and one peering
block per pair are spelled out here."""
REGIONS = ["us-east-1", "us-west-2", "eu-central-1", "ap-southeast-1", "sa-east-1"]
al = lambda r: r.replace("-", "_")

out = ["# Generated by gen.py; edit REGIONS there.\n"]
for i, r in enumerate(REGIONS):
    out.append(f'''provider "aws" {{
  alias  = "{al(r)}"
  region = "{r}"
}}
module "{al(r)}" {{
  source           = "./region"
  providers        = {{ aws = aws.{al(r)} }}
  nodes            = lookup(var.regions, "{r}", 0)
  coordinator      = var.home_region == "{r}"
  cidr             = "10.{i + 1}.0.0/16"
  instance_type    = var.instance_type
  coordinator_type = var.coordinator_type
  spot             = var.spot
  instance_profile = aws_iam_instance_profile.ssm.name
  cloud_init       = local.cloud_init
}}
''')
mods = ", ".join(f"module.{al(r)}" for r in REGIONS)
out.append(f'''locals {{
  supported = {REGIONS!r}
  modules   = [{mods}]
}}
output "coordinator_id" {{ value = one([for m in local.modules : m.coordinator_id if m.coordinator_id != null]) }}
output "coordinator_ip" {{ value = one([for m in local.modules : m.coordinator_ip if m.coordinator_ip != null]) }}
'''.replace("'", '"'))
open("regions.tf", "w").write("\n".join(out))

out = ["# Generated by gen.py. Full mesh of VPC peerings between the active regions.\n"]
for i, a in enumerate(REGIONS):
    for b in REGIONS[i + 1:]:
        n = f"{al(a)}__{al(b)}"
        out.append(f'''resource "aws_vpc_peering_connection" "{n}" {{
  count       = module.{al(a)}.active && module.{al(b)}.active ? 1 : 0
  provider    = aws.{al(a)}
  vpc_id      = module.{al(a)}.vpc_id
  peer_vpc_id = module.{al(b)}.vpc_id
  peer_region = "{b}"
}}
resource "aws_vpc_peering_connection_accepter" "{n}" {{
  count                     = module.{al(a)}.active && module.{al(b)}.active ? 1 : 0
  provider                  = aws.{al(b)}
  vpc_peering_connection_id = aws_vpc_peering_connection.{n}[0].id
  auto_accept               = true
}}
resource "aws_route" "{n}_ab" {{
  count                     = module.{al(a)}.active && module.{al(b)}.active ? 1 : 0
  provider                  = aws.{al(a)}
  route_table_id            = module.{al(a)}.route_table_id
  destination_cidr_block    = module.{al(b)}.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.{n}[0].id
}}
resource "aws_route" "{n}_ba" {{
  count                     = module.{al(a)}.active && module.{al(b)}.active ? 1 : 0
  provider                  = aws.{al(b)}
  route_table_id            = module.{al(b)}.route_table_id
  destination_cidr_block    = module.{al(a)}.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.{n}[0].id
}}
''')
open("peering.tf", "w").write("\n".join(out))
