# One node per instance across AWS regions. scenario.network.regions decides
# how many instances each region gets (`testbed fleet <scenario>` prints the
# `regions` variable); regions.tf and peering.tf are generated by gen.py for
# the supported region list. Private addressing throughout: VPCs are peered,
# instances have no public IPv4, shell access is through SSM.
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
provider "aws" {
  region = var.home_region
}

resource "aws_iam_role" "ssm" {
  name               = "topdisc-testbed-ssm"
  assume_role_policy = jsonencode({ Version = "2012-10-17", Statement = [{ Effect = "Allow", Principal = { Service = "ec2.amazonaws.com" }, Action = "sts:AssumeRole" }] })
}
resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.ssm.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}
# The coordinator lists the fleet in every region to build its inventory.
resource "aws_iam_role_policy_attachment" "ec2_read" {
  role       = aws_iam_role.ssm.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
}
resource "aws_iam_instance_profile" "ssm" {
  name = "topdisc-testbed-ssm"
  role = aws_iam_role.ssm.name
}

resource "aws_s3_bucket" "binaries" {
  bucket_prefix = "topdisc-testbed-"
  force_destroy = true
}
resource "aws_iam_role_policy" "s3" {
  name = "topdisc-binaries"
  role = aws_iam_role.ssm.id
  policy = jsonencode({ Version = "2012-10-17", Statement = [
    { Effect = "Allow", Action = ["s3:GetObject", "s3:PutObject"], Resource = "${aws_s3_bucket.binaries.arn}/*" },
    { Effect = "Allow", Action = ["s3:ListBucket"], Resource = aws_s3_bucket.binaries.arn },
  ] })
}

locals {
  cloud_init = templatefile("${path.module}/../../cloud-init.yaml.tftpl", {
    binaries_url = ""
    binaries_s3  = "s3://${aws_s3_bucket.binaries.id}/topdisc-linux-arm64.tgz"
    region       = var.home_region
    regions      = join(" ", sort(keys(var.regions)))
    max_hours    = var.max_hours
  })
}

# Spending cap. The budget alerts; the hard stop is the coordinator's
# fleet-scale-down timer (cloud-init), which scales every region's autoscaling
# group to zero max_hours after boot whatever happens to the laptop.
resource "aws_budgets_budget" "cap" {
  name         = "topdisc-testbed"
  budget_type  = "COST"
  limit_amount = var.max_spend_usd
  limit_unit   = "USD"
  time_unit    = "MONTHLY"
  dynamic "notification" {
    for_each = var.budget_email == "" ? [] : [50, 80, 100]
    content {
      comparison_operator        = "GREATER_THAN"
      threshold                  = notification.value
      threshold_type             = "PERCENTAGE"
      notification_type          = "ACTUAL"
      subscriber_email_addresses = [var.budget_email]
    }
  }
}
resource "aws_iam_role_policy" "scale_down" {
  name = "topdisc-scale-down"
  role = aws_iam_role.ssm.id
  policy = jsonencode({ Version = "2012-10-17", Statement = [
    { Effect = "Allow", Action = ["autoscaling:UpdateAutoScalingGroup", "autoscaling:SetDesiredCapacity", "autoscaling:DescribeAutoScalingGroups"], Resource = "*" },
  ] })
}
