# Generated by gen.py. Full mesh of VPC peerings between the active regions.

resource "aws_vpc_peering_connection" "us_east_1__us_west_2" {
  count       = module.us_east_1.active && module.us_west_2.active ? 1 : 0
  provider    = aws.us_east_1
  vpc_id      = module.us_east_1.vpc_id
  peer_vpc_id = module.us_west_2.vpc_id
  peer_region = "us-west-2"
}
resource "aws_vpc_peering_connection_accepter" "us_east_1__us_west_2" {
  count                     = module.us_east_1.active && module.us_west_2.active ? 1 : 0
  provider                  = aws.us_west_2
  vpc_peering_connection_id = aws_vpc_peering_connection.us_east_1__us_west_2[0].id
  auto_accept               = true
}
resource "aws_route" "us_east_1__us_west_2_ab" {
  count                     = module.us_east_1.active && module.us_west_2.active ? 1 : 0
  provider                  = aws.us_east_1
  route_table_id            = module.us_east_1.route_table_id
  destination_cidr_block    = module.us_west_2.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.us_east_1__us_west_2[0].id
}
resource "aws_route" "us_east_1__us_west_2_ba" {
  count                     = module.us_east_1.active && module.us_west_2.active ? 1 : 0
  provider                  = aws.us_west_2
  route_table_id            = module.us_west_2.route_table_id
  destination_cidr_block    = module.us_east_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.us_east_1__us_west_2[0].id
}

resource "aws_vpc_peering_connection" "us_east_1__eu_central_1" {
  count       = module.us_east_1.active && module.eu_central_1.active ? 1 : 0
  provider    = aws.us_east_1
  vpc_id      = module.us_east_1.vpc_id
  peer_vpc_id = module.eu_central_1.vpc_id
  peer_region = "eu-central-1"
}
resource "aws_vpc_peering_connection_accepter" "us_east_1__eu_central_1" {
  count                     = module.us_east_1.active && module.eu_central_1.active ? 1 : 0
  provider                  = aws.eu_central_1
  vpc_peering_connection_id = aws_vpc_peering_connection.us_east_1__eu_central_1[0].id
  auto_accept               = true
}
resource "aws_route" "us_east_1__eu_central_1_ab" {
  count                     = module.us_east_1.active && module.eu_central_1.active ? 1 : 0
  provider                  = aws.us_east_1
  route_table_id            = module.us_east_1.route_table_id
  destination_cidr_block    = module.eu_central_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.us_east_1__eu_central_1[0].id
}
resource "aws_route" "us_east_1__eu_central_1_ba" {
  count                     = module.us_east_1.active && module.eu_central_1.active ? 1 : 0
  provider                  = aws.eu_central_1
  route_table_id            = module.eu_central_1.route_table_id
  destination_cidr_block    = module.us_east_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.us_east_1__eu_central_1[0].id
}

resource "aws_vpc_peering_connection" "us_east_1__ap_southeast_1" {
  count       = module.us_east_1.active && module.ap_southeast_1.active ? 1 : 0
  provider    = aws.us_east_1
  vpc_id      = module.us_east_1.vpc_id
  peer_vpc_id = module.ap_southeast_1.vpc_id
  peer_region = "ap-southeast-1"
}
resource "aws_vpc_peering_connection_accepter" "us_east_1__ap_southeast_1" {
  count                     = module.us_east_1.active && module.ap_southeast_1.active ? 1 : 0
  provider                  = aws.ap_southeast_1
  vpc_peering_connection_id = aws_vpc_peering_connection.us_east_1__ap_southeast_1[0].id
  auto_accept               = true
}
resource "aws_route" "us_east_1__ap_southeast_1_ab" {
  count                     = module.us_east_1.active && module.ap_southeast_1.active ? 1 : 0
  provider                  = aws.us_east_1
  route_table_id            = module.us_east_1.route_table_id
  destination_cidr_block    = module.ap_southeast_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.us_east_1__ap_southeast_1[0].id
}
resource "aws_route" "us_east_1__ap_southeast_1_ba" {
  count                     = module.us_east_1.active && module.ap_southeast_1.active ? 1 : 0
  provider                  = aws.ap_southeast_1
  route_table_id            = module.ap_southeast_1.route_table_id
  destination_cidr_block    = module.us_east_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.us_east_1__ap_southeast_1[0].id
}

resource "aws_vpc_peering_connection" "us_east_1__sa_east_1" {
  count       = module.us_east_1.active && module.sa_east_1.active ? 1 : 0
  provider    = aws.us_east_1
  vpc_id      = module.us_east_1.vpc_id
  peer_vpc_id = module.sa_east_1.vpc_id
  peer_region = "sa-east-1"
}
resource "aws_vpc_peering_connection_accepter" "us_east_1__sa_east_1" {
  count                     = module.us_east_1.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.sa_east_1
  vpc_peering_connection_id = aws_vpc_peering_connection.us_east_1__sa_east_1[0].id
  auto_accept               = true
}
resource "aws_route" "us_east_1__sa_east_1_ab" {
  count                     = module.us_east_1.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.us_east_1
  route_table_id            = module.us_east_1.route_table_id
  destination_cidr_block    = module.sa_east_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.us_east_1__sa_east_1[0].id
}
resource "aws_route" "us_east_1__sa_east_1_ba" {
  count                     = module.us_east_1.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.sa_east_1
  route_table_id            = module.sa_east_1.route_table_id
  destination_cidr_block    = module.us_east_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.us_east_1__sa_east_1[0].id
}

resource "aws_vpc_peering_connection" "us_west_2__eu_central_1" {
  count       = module.us_west_2.active && module.eu_central_1.active ? 1 : 0
  provider    = aws.us_west_2
  vpc_id      = module.us_west_2.vpc_id
  peer_vpc_id = module.eu_central_1.vpc_id
  peer_region = "eu-central-1"
}
resource "aws_vpc_peering_connection_accepter" "us_west_2__eu_central_1" {
  count                     = module.us_west_2.active && module.eu_central_1.active ? 1 : 0
  provider                  = aws.eu_central_1
  vpc_peering_connection_id = aws_vpc_peering_connection.us_west_2__eu_central_1[0].id
  auto_accept               = true
}
resource "aws_route" "us_west_2__eu_central_1_ab" {
  count                     = module.us_west_2.active && module.eu_central_1.active ? 1 : 0
  provider                  = aws.us_west_2
  route_table_id            = module.us_west_2.route_table_id
  destination_cidr_block    = module.eu_central_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.us_west_2__eu_central_1[0].id
}
resource "aws_route" "us_west_2__eu_central_1_ba" {
  count                     = module.us_west_2.active && module.eu_central_1.active ? 1 : 0
  provider                  = aws.eu_central_1
  route_table_id            = module.eu_central_1.route_table_id
  destination_cidr_block    = module.us_west_2.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.us_west_2__eu_central_1[0].id
}

resource "aws_vpc_peering_connection" "us_west_2__ap_southeast_1" {
  count       = module.us_west_2.active && module.ap_southeast_1.active ? 1 : 0
  provider    = aws.us_west_2
  vpc_id      = module.us_west_2.vpc_id
  peer_vpc_id = module.ap_southeast_1.vpc_id
  peer_region = "ap-southeast-1"
}
resource "aws_vpc_peering_connection_accepter" "us_west_2__ap_southeast_1" {
  count                     = module.us_west_2.active && module.ap_southeast_1.active ? 1 : 0
  provider                  = aws.ap_southeast_1
  vpc_peering_connection_id = aws_vpc_peering_connection.us_west_2__ap_southeast_1[0].id
  auto_accept               = true
}
resource "aws_route" "us_west_2__ap_southeast_1_ab" {
  count                     = module.us_west_2.active && module.ap_southeast_1.active ? 1 : 0
  provider                  = aws.us_west_2
  route_table_id            = module.us_west_2.route_table_id
  destination_cidr_block    = module.ap_southeast_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.us_west_2__ap_southeast_1[0].id
}
resource "aws_route" "us_west_2__ap_southeast_1_ba" {
  count                     = module.us_west_2.active && module.ap_southeast_1.active ? 1 : 0
  provider                  = aws.ap_southeast_1
  route_table_id            = module.ap_southeast_1.route_table_id
  destination_cidr_block    = module.us_west_2.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.us_west_2__ap_southeast_1[0].id
}

resource "aws_vpc_peering_connection" "us_west_2__sa_east_1" {
  count       = module.us_west_2.active && module.sa_east_1.active ? 1 : 0
  provider    = aws.us_west_2
  vpc_id      = module.us_west_2.vpc_id
  peer_vpc_id = module.sa_east_1.vpc_id
  peer_region = "sa-east-1"
}
resource "aws_vpc_peering_connection_accepter" "us_west_2__sa_east_1" {
  count                     = module.us_west_2.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.sa_east_1
  vpc_peering_connection_id = aws_vpc_peering_connection.us_west_2__sa_east_1[0].id
  auto_accept               = true
}
resource "aws_route" "us_west_2__sa_east_1_ab" {
  count                     = module.us_west_2.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.us_west_2
  route_table_id            = module.us_west_2.route_table_id
  destination_cidr_block    = module.sa_east_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.us_west_2__sa_east_1[0].id
}
resource "aws_route" "us_west_2__sa_east_1_ba" {
  count                     = module.us_west_2.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.sa_east_1
  route_table_id            = module.sa_east_1.route_table_id
  destination_cidr_block    = module.us_west_2.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.us_west_2__sa_east_1[0].id
}

resource "aws_vpc_peering_connection" "eu_central_1__ap_southeast_1" {
  count       = module.eu_central_1.active && module.ap_southeast_1.active ? 1 : 0
  provider    = aws.eu_central_1
  vpc_id      = module.eu_central_1.vpc_id
  peer_vpc_id = module.ap_southeast_1.vpc_id
  peer_region = "ap-southeast-1"
}
resource "aws_vpc_peering_connection_accepter" "eu_central_1__ap_southeast_1" {
  count                     = module.eu_central_1.active && module.ap_southeast_1.active ? 1 : 0
  provider                  = aws.ap_southeast_1
  vpc_peering_connection_id = aws_vpc_peering_connection.eu_central_1__ap_southeast_1[0].id
  auto_accept               = true
}
resource "aws_route" "eu_central_1__ap_southeast_1_ab" {
  count                     = module.eu_central_1.active && module.ap_southeast_1.active ? 1 : 0
  provider                  = aws.eu_central_1
  route_table_id            = module.eu_central_1.route_table_id
  destination_cidr_block    = module.ap_southeast_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.eu_central_1__ap_southeast_1[0].id
}
resource "aws_route" "eu_central_1__ap_southeast_1_ba" {
  count                     = module.eu_central_1.active && module.ap_southeast_1.active ? 1 : 0
  provider                  = aws.ap_southeast_1
  route_table_id            = module.ap_southeast_1.route_table_id
  destination_cidr_block    = module.eu_central_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.eu_central_1__ap_southeast_1[0].id
}

resource "aws_vpc_peering_connection" "eu_central_1__sa_east_1" {
  count       = module.eu_central_1.active && module.sa_east_1.active ? 1 : 0
  provider    = aws.eu_central_1
  vpc_id      = module.eu_central_1.vpc_id
  peer_vpc_id = module.sa_east_1.vpc_id
  peer_region = "sa-east-1"
}
resource "aws_vpc_peering_connection_accepter" "eu_central_1__sa_east_1" {
  count                     = module.eu_central_1.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.sa_east_1
  vpc_peering_connection_id = aws_vpc_peering_connection.eu_central_1__sa_east_1[0].id
  auto_accept               = true
}
resource "aws_route" "eu_central_1__sa_east_1_ab" {
  count                     = module.eu_central_1.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.eu_central_1
  route_table_id            = module.eu_central_1.route_table_id
  destination_cidr_block    = module.sa_east_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.eu_central_1__sa_east_1[0].id
}
resource "aws_route" "eu_central_1__sa_east_1_ba" {
  count                     = module.eu_central_1.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.sa_east_1
  route_table_id            = module.sa_east_1.route_table_id
  destination_cidr_block    = module.eu_central_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.eu_central_1__sa_east_1[0].id
}

resource "aws_vpc_peering_connection" "ap_southeast_1__sa_east_1" {
  count       = module.ap_southeast_1.active && module.sa_east_1.active ? 1 : 0
  provider    = aws.ap_southeast_1
  vpc_id      = module.ap_southeast_1.vpc_id
  peer_vpc_id = module.sa_east_1.vpc_id
  peer_region = "sa-east-1"
}
resource "aws_vpc_peering_connection_accepter" "ap_southeast_1__sa_east_1" {
  count                     = module.ap_southeast_1.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.sa_east_1
  vpc_peering_connection_id = aws_vpc_peering_connection.ap_southeast_1__sa_east_1[0].id
  auto_accept               = true
}
resource "aws_route" "ap_southeast_1__sa_east_1_ab" {
  count                     = module.ap_southeast_1.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.ap_southeast_1
  route_table_id            = module.ap_southeast_1.route_table_id
  destination_cidr_block    = module.sa_east_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.ap_southeast_1__sa_east_1[0].id
}
resource "aws_route" "ap_southeast_1__sa_east_1_ba" {
  count                     = module.ap_southeast_1.active && module.sa_east_1.active ? 1 : 0
  provider                  = aws.sa_east_1
  route_table_id            = module.sa_east_1.route_table_id
  destination_cidr_block    = module.ap_southeast_1.cidr
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.ap_southeast_1__sa_east_1[0].id
}
