# Generated by gen.py; edit REGIONS there.

provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"
}
module "us_east_1" {
  source           = "./region"
  providers        = { aws = aws.us_east_1 }
  nodes            = lookup(var.regions, "us-east-1", 0)
  coordinator      = var.home_region == "us-east-1"
  cidr             = "10.1.0.0/16"
  instance_type    = var.instance_type
  coordinator_type = var.coordinator_type
  spot             = var.spot
  instance_profile = aws_iam_instance_profile.ssm.name
  cloud_init       = local.cloud_init
}

provider "aws" {
  alias  = "us_west_2"
  region = "us-west-2"
}
module "us_west_2" {
  source           = "./region"
  providers        = { aws = aws.us_west_2 }
  nodes            = lookup(var.regions, "us-west-2", 0)
  coordinator      = var.home_region == "us-west-2"
  cidr             = "10.2.0.0/16"
  instance_type    = var.instance_type
  coordinator_type = var.coordinator_type
  spot             = var.spot
  instance_profile = aws_iam_instance_profile.ssm.name
  cloud_init       = local.cloud_init
}

provider "aws" {
  alias  = "eu_central_1"
  region = "eu-central-1"
}
module "eu_central_1" {
  source           = "./region"
  providers        = { aws = aws.eu_central_1 }
  nodes            = lookup(var.regions, "eu-central-1", 0)
  coordinator      = var.home_region == "eu-central-1"
  cidr             = "10.3.0.0/16"
  instance_type    = var.instance_type
  coordinator_type = var.coordinator_type
  spot             = var.spot
  instance_profile = aws_iam_instance_profile.ssm.name
  cloud_init       = local.cloud_init
}

provider "aws" {
  alias  = "ap_southeast_1"
  region = "ap-southeast-1"
}
module "ap_southeast_1" {
  source           = "./region"
  providers        = { aws = aws.ap_southeast_1 }
  nodes            = lookup(var.regions, "ap-southeast-1", 0)
  coordinator      = var.home_region == "ap-southeast-1"
  cidr             = "10.4.0.0/16"
  instance_type    = var.instance_type
  coordinator_type = var.coordinator_type
  spot             = var.spot
  instance_profile = aws_iam_instance_profile.ssm.name
  cloud_init       = local.cloud_init
}

provider "aws" {
  alias  = "sa_east_1"
  region = "sa-east-1"
}
module "sa_east_1" {
  source           = "./region"
  providers        = { aws = aws.sa_east_1 }
  nodes            = lookup(var.regions, "sa-east-1", 0)
  coordinator      = var.home_region == "sa-east-1"
  cidr             = "10.5.0.0/16"
  instance_type    = var.instance_type
  coordinator_type = var.coordinator_type
  spot             = var.spot
  instance_profile = aws_iam_instance_profile.ssm.name
  cloud_init       = local.cloud_init
}

locals {
  supported = ["us-east-1", "us-west-2", "eu-central-1", "ap-southeast-1", "sa-east-1"]
  modules   = [module.us_east_1, module.us_west_2, module.eu_central_1, module.ap_southeast_1, module.sa_east_1]
}
output "coordinator_id" { value = one([for m in local.modules : m.coordinator_id if m.coordinator_id != null]) }
output "coordinator_ip" { value = one([for m in local.modules : m.coordinator_ip if m.coordinator_ip != null]) }
